version: "3.9"

services:
  # web server: nginx
  web:
    container_name: web
    image: nginx:$NGINX_TAG
    volumes:
      - ./build/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  # app server: node
  app:
    container_name: app
    #image: node:$NODE_TAG
    build:
      context: build/app
      dockerfile: Dockerfile
      args:
        - NODE_TAG=$NODE_TAG
        - USERNAME=$USERNAME
        - UID=$UID
        - APP_DIR=$APP_DIR
    volumes:
      - $APP_DIR
      - node_modules:$APP_DIR/node_modules
    tty: true
    ports:
      - "3000:3000"

volumes:
  node_modules:
